Repository Homebrodot/Godot, pull requests merged in 2024-01, with the labels that each got.

#4 Add get and set functions for joypad motion sensors
  core/os/input.cpp
  core/os/input.h
  doc/classes/Input.xml
  main/input_default.cpp
  main/input_default.h
Labels: documentation, enhancement

#8 [Switch] Fix OS_Switch::show_virtual_keyboard
  platform/switch/os_switch.cpp
  platform/switch/os_switch.h
Labels: bug, good first issue

#3 [Switch] Separate the Audren driver into its own directory
  drivers/SCsub
  drivers/audren/SCsub
  drivers/audren/audio_driver_audren.cpp
  drivers/audren/audio_driver_audren.h
  platform/switch/SCsub
  platform/switch/os_switch.cpp
  platform/switch/os_switch.h
Labels: enhancement

#5 [3.5 | Switch] Implement LibNX psm.h for power_switch.cpp
  platform/switch/SCsub
  platform/switch/os_switch.cpp
  platform/switch/os_switch.h
  platform/switch/power_switch.cpp
  platform/switch/power_switch.h
Labels: enhancement

#7 Disable homebrew exporters on Mono editors
  platform/switch/export/export.h
  platform/vita/export/export.h
Labels: bug
